import AirConditions from '@/components/AirConditions'
import CityForecast from '@/components/CityForecast'
import CitySearch from '@/components/CitySearch'
import FiveDayForecast from '@/components/FiveDayForecast'
import TodayForecast from '@/components/TodayForecast'
import { WeatherProvider } from '@/context/WeatherContext'
import Head from 'next/head'

export default function Home() {
 
  return (
    <>
      <Head>
        <title>Next Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WeatherProvider>
          <div className='flex flex-col gap-8 lg:flex-row'>
            <div className='flex-1'>
              <CitySearch />
              <CityForecast />
              <TodayForecast />
              <AirConditions />
            </div>
            <FiveDayForecast />
          </div>
        </WeatherProvider>

      </main>
    </>
  )
}
