import Head from 'next/head'

export default function Home() {
  // fetch(`https://api.openweathermap.org/data/2.5/forecast?lat=41.0053&lon=28.9770&appid=95f9a7f17708953d5d2637aef6d30157`)
  // .then(resp => resp.json())
  // .then(data => console.log(data))
  return (
    <>
      <Head>
        <title>Next Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Weather App</h1>
      </main>
    </>
  )
}
